version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: vehicles-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/my_config/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_server:/pgadmin4/my_config

volumes:
  postgres_data:
