version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: vehicles-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      # Performance tuning
      POSTGRES_EXTRA_CONFIG: |
        shared_buffers = 512MB
        work_mem = 16MB
        maintenance_work_mem = 128MB
        effective_cache_size = 1GB
        max_connections = 100
        wal_buffers = 16MB
        checkpoint_completion_target = 0.9
        random_page_cost = 1.1
        effective_io_concurrency = 200
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    build:
      context: .
      shm_size: 512mb
    shm_size: 1024mb
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1024M

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/my_config/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_server:/pgadmin4/my_config

volumes:
  postgres_data:
